/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.integrations.orderprocessing.kafka.schema;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class CarrierTrkgDlvry extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 7155087284416918004L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"CarrierTrkgDlvry\",\"namespace\":\"com.integrations.orderprocessing.kafka.schema\",\"fields\":[{\"name\":\"containerNumber\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"customerLoadId\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"manifestNumber\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"parcelTrackNumber\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"proNumber\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"sealNumber\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"totalNoofWMSShipmentsInTruck\",\"type\":\"int\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<CarrierTrkgDlvry> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<CarrierTrkgDlvry> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<CarrierTrkgDlvry> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<CarrierTrkgDlvry> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<CarrierTrkgDlvry> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this CarrierTrkgDlvry to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a CarrierTrkgDlvry from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a CarrierTrkgDlvry instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static CarrierTrkgDlvry fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private java.lang.String containerNumber;
  private java.lang.String customerLoadId;
  private java.lang.String manifestNumber;
  private java.lang.String parcelTrackNumber;
  private java.lang.String proNumber;
  private java.lang.String sealNumber;
  private int totalNoofWMSShipmentsInTruck;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public CarrierTrkgDlvry() {}

  /**
   * All-args constructor.
   * @param containerNumber The new value for containerNumber
   * @param customerLoadId The new value for customerLoadId
   * @param manifestNumber The new value for manifestNumber
   * @param parcelTrackNumber The new value for parcelTrackNumber
   * @param proNumber The new value for proNumber
   * @param sealNumber The new value for sealNumber
   * @param totalNoofWMSShipmentsInTruck The new value for totalNoofWMSShipmentsInTruck
   */
  public CarrierTrkgDlvry(java.lang.String containerNumber, java.lang.String customerLoadId, java.lang.String manifestNumber, java.lang.String parcelTrackNumber, java.lang.String proNumber, java.lang.String sealNumber, java.lang.Integer totalNoofWMSShipmentsInTruck) {
    this.containerNumber = containerNumber;
    this.customerLoadId = customerLoadId;
    this.manifestNumber = manifestNumber;
    this.parcelTrackNumber = parcelTrackNumber;
    this.proNumber = proNumber;
    this.sealNumber = sealNumber;
    this.totalNoofWMSShipmentsInTruck = totalNoofWMSShipmentsInTruck;
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return containerNumber;
    case 1: return customerLoadId;
    case 2: return manifestNumber;
    case 3: return parcelTrackNumber;
    case 4: return proNumber;
    case 5: return sealNumber;
    case 6: return totalNoofWMSShipmentsInTruck;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: containerNumber = value$ != null ? value$.toString() : null; break;
    case 1: customerLoadId = value$ != null ? value$.toString() : null; break;
    case 2: manifestNumber = value$ != null ? value$.toString() : null; break;
    case 3: parcelTrackNumber = value$ != null ? value$.toString() : null; break;
    case 4: proNumber = value$ != null ? value$.toString() : null; break;
    case 5: sealNumber = value$ != null ? value$.toString() : null; break;
    case 6: totalNoofWMSShipmentsInTruck = (java.lang.Integer)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'containerNumber' field.
   * @return The value of the 'containerNumber' field.
   */
  public java.lang.String getContainerNumber() {
    return containerNumber;
  }


  /**
   * Sets the value of the 'containerNumber' field.
   * @param value the value to set.
   */
  public void setContainerNumber(java.lang.String value) {
    this.containerNumber = value;
  }

  /**
   * Gets the value of the 'customerLoadId' field.
   * @return The value of the 'customerLoadId' field.
   */
  public java.lang.String getCustomerLoadId() {
    return customerLoadId;
  }


  /**
   * Sets the value of the 'customerLoadId' field.
   * @param value the value to set.
   */
  public void setCustomerLoadId(java.lang.String value) {
    this.customerLoadId = value;
  }

  /**
   * Gets the value of the 'manifestNumber' field.
   * @return The value of the 'manifestNumber' field.
   */
  public java.lang.String getManifestNumber() {
    return manifestNumber;
  }


  /**
   * Sets the value of the 'manifestNumber' field.
   * @param value the value to set.
   */
  public void setManifestNumber(java.lang.String value) {
    this.manifestNumber = value;
  }

  /**
   * Gets the value of the 'parcelTrackNumber' field.
   * @return The value of the 'parcelTrackNumber' field.
   */
  public java.lang.String getParcelTrackNumber() {
    return parcelTrackNumber;
  }


  /**
   * Sets the value of the 'parcelTrackNumber' field.
   * @param value the value to set.
   */
  public void setParcelTrackNumber(java.lang.String value) {
    this.parcelTrackNumber = value;
  }

  /**
   * Gets the value of the 'proNumber' field.
   * @return The value of the 'proNumber' field.
   */
  public java.lang.String getProNumber() {
    return proNumber;
  }


  /**
   * Sets the value of the 'proNumber' field.
   * @param value the value to set.
   */
  public void setProNumber(java.lang.String value) {
    this.proNumber = value;
  }

  /**
   * Gets the value of the 'sealNumber' field.
   * @return The value of the 'sealNumber' field.
   */
  public java.lang.String getSealNumber() {
    return sealNumber;
  }


  /**
   * Sets the value of the 'sealNumber' field.
   * @param value the value to set.
   */
  public void setSealNumber(java.lang.String value) {
    this.sealNumber = value;
  }

  /**
   * Gets the value of the 'totalNoofWMSShipmentsInTruck' field.
   * @return The value of the 'totalNoofWMSShipmentsInTruck' field.
   */
  public int getTotalNoofWMSShipmentsInTruck() {
    return totalNoofWMSShipmentsInTruck;
  }


  /**
   * Sets the value of the 'totalNoofWMSShipmentsInTruck' field.
   * @param value the value to set.
   */
  public void setTotalNoofWMSShipmentsInTruck(int value) {
    this.totalNoofWMSShipmentsInTruck = value;
  }

  /**
   * Creates a new CarrierTrkgDlvry RecordBuilder.
   * @return A new CarrierTrkgDlvry RecordBuilder
   */
  public static com.integrations.orderprocessing.kafka.schema.CarrierTrkgDlvry.Builder newBuilder() {
    return new com.integrations.orderprocessing.kafka.schema.CarrierTrkgDlvry.Builder();
  }

  /**
   * Creates a new CarrierTrkgDlvry RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new CarrierTrkgDlvry RecordBuilder
   */
  public static com.integrations.orderprocessing.kafka.schema.CarrierTrkgDlvry.Builder newBuilder(com.integrations.orderprocessing.kafka.schema.CarrierTrkgDlvry.Builder other) {
    if (other == null) {
      return new com.integrations.orderprocessing.kafka.schema.CarrierTrkgDlvry.Builder();
    } else {
      return new com.integrations.orderprocessing.kafka.schema.CarrierTrkgDlvry.Builder(other);
    }
  }

  /**
   * Creates a new CarrierTrkgDlvry RecordBuilder by copying an existing CarrierTrkgDlvry instance.
   * @param other The existing instance to copy.
   * @return A new CarrierTrkgDlvry RecordBuilder
   */
  public static com.integrations.orderprocessing.kafka.schema.CarrierTrkgDlvry.Builder newBuilder(com.integrations.orderprocessing.kafka.schema.CarrierTrkgDlvry other) {
    if (other == null) {
      return new com.integrations.orderprocessing.kafka.schema.CarrierTrkgDlvry.Builder();
    } else {
      return new com.integrations.orderprocessing.kafka.schema.CarrierTrkgDlvry.Builder(other);
    }
  }

  /**
   * RecordBuilder for CarrierTrkgDlvry instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<CarrierTrkgDlvry>
    implements org.apache.avro.data.RecordBuilder<CarrierTrkgDlvry> {

    private java.lang.String containerNumber;
    private java.lang.String customerLoadId;
    private java.lang.String manifestNumber;
    private java.lang.String parcelTrackNumber;
    private java.lang.String proNumber;
    private java.lang.String sealNumber;
    private int totalNoofWMSShipmentsInTruck;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.integrations.orderprocessing.kafka.schema.CarrierTrkgDlvry.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.containerNumber)) {
        this.containerNumber = data().deepCopy(fields()[0].schema(), other.containerNumber);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.customerLoadId)) {
        this.customerLoadId = data().deepCopy(fields()[1].schema(), other.customerLoadId);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.manifestNumber)) {
        this.manifestNumber = data().deepCopy(fields()[2].schema(), other.manifestNumber);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.parcelTrackNumber)) {
        this.parcelTrackNumber = data().deepCopy(fields()[3].schema(), other.parcelTrackNumber);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
      if (isValidValue(fields()[4], other.proNumber)) {
        this.proNumber = data().deepCopy(fields()[4].schema(), other.proNumber);
        fieldSetFlags()[4] = other.fieldSetFlags()[4];
      }
      if (isValidValue(fields()[5], other.sealNumber)) {
        this.sealNumber = data().deepCopy(fields()[5].schema(), other.sealNumber);
        fieldSetFlags()[5] = other.fieldSetFlags()[5];
      }
      if (isValidValue(fields()[6], other.totalNoofWMSShipmentsInTruck)) {
        this.totalNoofWMSShipmentsInTruck = data().deepCopy(fields()[6].schema(), other.totalNoofWMSShipmentsInTruck);
        fieldSetFlags()[6] = other.fieldSetFlags()[6];
      }
    }

    /**
     * Creates a Builder by copying an existing CarrierTrkgDlvry instance
     * @param other The existing instance to copy.
     */
    private Builder(com.integrations.orderprocessing.kafka.schema.CarrierTrkgDlvry other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.containerNumber)) {
        this.containerNumber = data().deepCopy(fields()[0].schema(), other.containerNumber);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.customerLoadId)) {
        this.customerLoadId = data().deepCopy(fields()[1].schema(), other.customerLoadId);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.manifestNumber)) {
        this.manifestNumber = data().deepCopy(fields()[2].schema(), other.manifestNumber);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.parcelTrackNumber)) {
        this.parcelTrackNumber = data().deepCopy(fields()[3].schema(), other.parcelTrackNumber);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.proNumber)) {
        this.proNumber = data().deepCopy(fields()[4].schema(), other.proNumber);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.sealNumber)) {
        this.sealNumber = data().deepCopy(fields()[5].schema(), other.sealNumber);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.totalNoofWMSShipmentsInTruck)) {
        this.totalNoofWMSShipmentsInTruck = data().deepCopy(fields()[6].schema(), other.totalNoofWMSShipmentsInTruck);
        fieldSetFlags()[6] = true;
      }
    }

    /**
      * Gets the value of the 'containerNumber' field.
      * @return The value.
      */
    public java.lang.String getContainerNumber() {
      return containerNumber;
    }


    /**
      * Sets the value of the 'containerNumber' field.
      * @param value The value of 'containerNumber'.
      * @return This builder.
      */
    public com.integrations.orderprocessing.kafka.schema.CarrierTrkgDlvry.Builder setContainerNumber(java.lang.String value) {
      validate(fields()[0], value);
      this.containerNumber = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'containerNumber' field has been set.
      * @return True if the 'containerNumber' field has been set, false otherwise.
      */
    public boolean hasContainerNumber() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'containerNumber' field.
      * @return This builder.
      */
    public com.integrations.orderprocessing.kafka.schema.CarrierTrkgDlvry.Builder clearContainerNumber() {
      containerNumber = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'customerLoadId' field.
      * @return The value.
      */
    public java.lang.String getCustomerLoadId() {
      return customerLoadId;
    }


    /**
      * Sets the value of the 'customerLoadId' field.
      * @param value The value of 'customerLoadId'.
      * @return This builder.
      */
    public com.integrations.orderprocessing.kafka.schema.CarrierTrkgDlvry.Builder setCustomerLoadId(java.lang.String value) {
      validate(fields()[1], value);
      this.customerLoadId = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'customerLoadId' field has been set.
      * @return True if the 'customerLoadId' field has been set, false otherwise.
      */
    public boolean hasCustomerLoadId() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'customerLoadId' field.
      * @return This builder.
      */
    public com.integrations.orderprocessing.kafka.schema.CarrierTrkgDlvry.Builder clearCustomerLoadId() {
      customerLoadId = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'manifestNumber' field.
      * @return The value.
      */
    public java.lang.String getManifestNumber() {
      return manifestNumber;
    }


    /**
      * Sets the value of the 'manifestNumber' field.
      * @param value The value of 'manifestNumber'.
      * @return This builder.
      */
    public com.integrations.orderprocessing.kafka.schema.CarrierTrkgDlvry.Builder setManifestNumber(java.lang.String value) {
      validate(fields()[2], value);
      this.manifestNumber = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'manifestNumber' field has been set.
      * @return True if the 'manifestNumber' field has been set, false otherwise.
      */
    public boolean hasManifestNumber() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'manifestNumber' field.
      * @return This builder.
      */
    public com.integrations.orderprocessing.kafka.schema.CarrierTrkgDlvry.Builder clearManifestNumber() {
      manifestNumber = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'parcelTrackNumber' field.
      * @return The value.
      */
    public java.lang.String getParcelTrackNumber() {
      return parcelTrackNumber;
    }


    /**
      * Sets the value of the 'parcelTrackNumber' field.
      * @param value The value of 'parcelTrackNumber'.
      * @return This builder.
      */
    public com.integrations.orderprocessing.kafka.schema.CarrierTrkgDlvry.Builder setParcelTrackNumber(java.lang.String value) {
      validate(fields()[3], value);
      this.parcelTrackNumber = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'parcelTrackNumber' field has been set.
      * @return True if the 'parcelTrackNumber' field has been set, false otherwise.
      */
    public boolean hasParcelTrackNumber() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'parcelTrackNumber' field.
      * @return This builder.
      */
    public com.integrations.orderprocessing.kafka.schema.CarrierTrkgDlvry.Builder clearParcelTrackNumber() {
      parcelTrackNumber = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'proNumber' field.
      * @return The value.
      */
    public java.lang.String getProNumber() {
      return proNumber;
    }


    /**
      * Sets the value of the 'proNumber' field.
      * @param value The value of 'proNumber'.
      * @return This builder.
      */
    public com.integrations.orderprocessing.kafka.schema.CarrierTrkgDlvry.Builder setProNumber(java.lang.String value) {
      validate(fields()[4], value);
      this.proNumber = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'proNumber' field has been set.
      * @return True if the 'proNumber' field has been set, false otherwise.
      */
    public boolean hasProNumber() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'proNumber' field.
      * @return This builder.
      */
    public com.integrations.orderprocessing.kafka.schema.CarrierTrkgDlvry.Builder clearProNumber() {
      proNumber = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    /**
      * Gets the value of the 'sealNumber' field.
      * @return The value.
      */
    public java.lang.String getSealNumber() {
      return sealNumber;
    }


    /**
      * Sets the value of the 'sealNumber' field.
      * @param value The value of 'sealNumber'.
      * @return This builder.
      */
    public com.integrations.orderprocessing.kafka.schema.CarrierTrkgDlvry.Builder setSealNumber(java.lang.String value) {
      validate(fields()[5], value);
      this.sealNumber = value;
      fieldSetFlags()[5] = true;
      return this;
    }

    /**
      * Checks whether the 'sealNumber' field has been set.
      * @return True if the 'sealNumber' field has been set, false otherwise.
      */
    public boolean hasSealNumber() {
      return fieldSetFlags()[5];
    }


    /**
      * Clears the value of the 'sealNumber' field.
      * @return This builder.
      */
    public com.integrations.orderprocessing.kafka.schema.CarrierTrkgDlvry.Builder clearSealNumber() {
      sealNumber = null;
      fieldSetFlags()[5] = false;
      return this;
    }

    /**
      * Gets the value of the 'totalNoofWMSShipmentsInTruck' field.
      * @return The value.
      */
    public int getTotalNoofWMSShipmentsInTruck() {
      return totalNoofWMSShipmentsInTruck;
    }


    /**
      * Sets the value of the 'totalNoofWMSShipmentsInTruck' field.
      * @param value The value of 'totalNoofWMSShipmentsInTruck'.
      * @return This builder.
      */
    public com.integrations.orderprocessing.kafka.schema.CarrierTrkgDlvry.Builder setTotalNoofWMSShipmentsInTruck(int value) {
      validate(fields()[6], value);
      this.totalNoofWMSShipmentsInTruck = value;
      fieldSetFlags()[6] = true;
      return this;
    }

    /**
      * Checks whether the 'totalNoofWMSShipmentsInTruck' field has been set.
      * @return True if the 'totalNoofWMSShipmentsInTruck' field has been set, false otherwise.
      */
    public boolean hasTotalNoofWMSShipmentsInTruck() {
      return fieldSetFlags()[6];
    }


    /**
      * Clears the value of the 'totalNoofWMSShipmentsInTruck' field.
      * @return This builder.
      */
    public com.integrations.orderprocessing.kafka.schema.CarrierTrkgDlvry.Builder clearTotalNoofWMSShipmentsInTruck() {
      fieldSetFlags()[6] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public CarrierTrkgDlvry build() {
      try {
        CarrierTrkgDlvry record = new CarrierTrkgDlvry();
        record.containerNumber = fieldSetFlags()[0] ? this.containerNumber : (java.lang.String) defaultValue(fields()[0]);
        record.customerLoadId = fieldSetFlags()[1] ? this.customerLoadId : (java.lang.String) defaultValue(fields()[1]);
        record.manifestNumber = fieldSetFlags()[2] ? this.manifestNumber : (java.lang.String) defaultValue(fields()[2]);
        record.parcelTrackNumber = fieldSetFlags()[3] ? this.parcelTrackNumber : (java.lang.String) defaultValue(fields()[3]);
        record.proNumber = fieldSetFlags()[4] ? this.proNumber : (java.lang.String) defaultValue(fields()[4]);
        record.sealNumber = fieldSetFlags()[5] ? this.sealNumber : (java.lang.String) defaultValue(fields()[5]);
        record.totalNoofWMSShipmentsInTruck = fieldSetFlags()[6] ? this.totalNoofWMSShipmentsInTruck : (java.lang.Integer) defaultValue(fields()[6]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<CarrierTrkgDlvry>
    WRITER$ = (org.apache.avro.io.DatumWriter<CarrierTrkgDlvry>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<CarrierTrkgDlvry>
    READER$ = (org.apache.avro.io.DatumReader<CarrierTrkgDlvry>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.containerNumber);

    out.writeString(this.customerLoadId);

    out.writeString(this.manifestNumber);

    out.writeString(this.parcelTrackNumber);

    out.writeString(this.proNumber);

    out.writeString(this.sealNumber);

    out.writeInt(this.totalNoofWMSShipmentsInTruck);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.containerNumber = in.readString();

      this.customerLoadId = in.readString();

      this.manifestNumber = in.readString();

      this.parcelTrackNumber = in.readString();

      this.proNumber = in.readString();

      this.sealNumber = in.readString();

      this.totalNoofWMSShipmentsInTruck = in.readInt();

    } else {
      for (int i = 0; i < 7; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.containerNumber = in.readString();
          break;

        case 1:
          this.customerLoadId = in.readString();
          break;

        case 2:
          this.manifestNumber = in.readString();
          break;

        case 3:
          this.parcelTrackNumber = in.readString();
          break;

        case 4:
          this.proNumber = in.readString();
          break;

        case 5:
          this.sealNumber = in.readString();
          break;

        case 6:
          this.totalNoofWMSShipmentsInTruck = in.readInt();
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










