/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.integrations.orderprocessing.kafka.schema;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class ItemLabelDetails extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -4254180908506467532L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"ItemLabelDetails\",\"namespace\":\"com.integrations.orderprocessing.kafka.schema\",\"fields\":[{\"name\":\"cartonLabelId\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"labelType\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"palletLabelId\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"palletNumber\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"quantity\",\"type\":\"int\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<ItemLabelDetails> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<ItemLabelDetails> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<ItemLabelDetails> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<ItemLabelDetails> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<ItemLabelDetails> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this ItemLabelDetails to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a ItemLabelDetails from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a ItemLabelDetails instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static ItemLabelDetails fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private java.lang.String cartonLabelId;
  private java.lang.String labelType;
  private java.lang.String palletLabelId;
  private java.lang.String palletNumber;
  private int quantity;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public ItemLabelDetails() {}

  /**
   * All-args constructor.
   * @param cartonLabelId The new value for cartonLabelId
   * @param labelType The new value for labelType
   * @param palletLabelId The new value for palletLabelId
   * @param palletNumber The new value for palletNumber
   * @param quantity The new value for quantity
   */
  public ItemLabelDetails(java.lang.String cartonLabelId, java.lang.String labelType, java.lang.String palletLabelId, java.lang.String palletNumber, java.lang.Integer quantity) {
    this.cartonLabelId = cartonLabelId;
    this.labelType = labelType;
    this.palletLabelId = palletLabelId;
    this.palletNumber = palletNumber;
    this.quantity = quantity;
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return cartonLabelId;
    case 1: return labelType;
    case 2: return palletLabelId;
    case 3: return palletNumber;
    case 4: return quantity;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: cartonLabelId = value$ != null ? value$.toString() : null; break;
    case 1: labelType = value$ != null ? value$.toString() : null; break;
    case 2: palletLabelId = value$ != null ? value$.toString() : null; break;
    case 3: palletNumber = value$ != null ? value$.toString() : null; break;
    case 4: quantity = (java.lang.Integer)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'cartonLabelId' field.
   * @return The value of the 'cartonLabelId' field.
   */
  public java.lang.String getCartonLabelId() {
    return cartonLabelId;
  }


  /**
   * Sets the value of the 'cartonLabelId' field.
   * @param value the value to set.
   */
  public void setCartonLabelId(java.lang.String value) {
    this.cartonLabelId = value;
  }

  /**
   * Gets the value of the 'labelType' field.
   * @return The value of the 'labelType' field.
   */
  public java.lang.String getLabelType() {
    return labelType;
  }


  /**
   * Sets the value of the 'labelType' field.
   * @param value the value to set.
   */
  public void setLabelType(java.lang.String value) {
    this.labelType = value;
  }

  /**
   * Gets the value of the 'palletLabelId' field.
   * @return The value of the 'palletLabelId' field.
   */
  public java.lang.String getPalletLabelId() {
    return palletLabelId;
  }


  /**
   * Sets the value of the 'palletLabelId' field.
   * @param value the value to set.
   */
  public void setPalletLabelId(java.lang.String value) {
    this.palletLabelId = value;
  }

  /**
   * Gets the value of the 'palletNumber' field.
   * @return The value of the 'palletNumber' field.
   */
  public java.lang.String getPalletNumber() {
    return palletNumber;
  }


  /**
   * Sets the value of the 'palletNumber' field.
   * @param value the value to set.
   */
  public void setPalletNumber(java.lang.String value) {
    this.palletNumber = value;
  }

  /**
   * Gets the value of the 'quantity' field.
   * @return The value of the 'quantity' field.
   */
  public int getQuantity() {
    return quantity;
  }


  /**
   * Sets the value of the 'quantity' field.
   * @param value the value to set.
   */
  public void setQuantity(int value) {
    this.quantity = value;
  }

  /**
   * Creates a new ItemLabelDetails RecordBuilder.
   * @return A new ItemLabelDetails RecordBuilder
   */
  public static com.integrations.orderprocessing.kafka.schema.ItemLabelDetails.Builder newBuilder() {
    return new com.integrations.orderprocessing.kafka.schema.ItemLabelDetails.Builder();
  }

  /**
   * Creates a new ItemLabelDetails RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new ItemLabelDetails RecordBuilder
   */
  public static com.integrations.orderprocessing.kafka.schema.ItemLabelDetails.Builder newBuilder(com.integrations.orderprocessing.kafka.schema.ItemLabelDetails.Builder other) {
    if (other == null) {
      return new com.integrations.orderprocessing.kafka.schema.ItemLabelDetails.Builder();
    } else {
      return new com.integrations.orderprocessing.kafka.schema.ItemLabelDetails.Builder(other);
    }
  }

  /**
   * Creates a new ItemLabelDetails RecordBuilder by copying an existing ItemLabelDetails instance.
   * @param other The existing instance to copy.
   * @return A new ItemLabelDetails RecordBuilder
   */
  public static com.integrations.orderprocessing.kafka.schema.ItemLabelDetails.Builder newBuilder(com.integrations.orderprocessing.kafka.schema.ItemLabelDetails other) {
    if (other == null) {
      return new com.integrations.orderprocessing.kafka.schema.ItemLabelDetails.Builder();
    } else {
      return new com.integrations.orderprocessing.kafka.schema.ItemLabelDetails.Builder(other);
    }
  }

  /**
   * RecordBuilder for ItemLabelDetails instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<ItemLabelDetails>
    implements org.apache.avro.data.RecordBuilder<ItemLabelDetails> {

    private java.lang.String cartonLabelId;
    private java.lang.String labelType;
    private java.lang.String palletLabelId;
    private java.lang.String palletNumber;
    private int quantity;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.integrations.orderprocessing.kafka.schema.ItemLabelDetails.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.cartonLabelId)) {
        this.cartonLabelId = data().deepCopy(fields()[0].schema(), other.cartonLabelId);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.labelType)) {
        this.labelType = data().deepCopy(fields()[1].schema(), other.labelType);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.palletLabelId)) {
        this.palletLabelId = data().deepCopy(fields()[2].schema(), other.palletLabelId);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.palletNumber)) {
        this.palletNumber = data().deepCopy(fields()[3].schema(), other.palletNumber);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
      if (isValidValue(fields()[4], other.quantity)) {
        this.quantity = data().deepCopy(fields()[4].schema(), other.quantity);
        fieldSetFlags()[4] = other.fieldSetFlags()[4];
      }
    }

    /**
     * Creates a Builder by copying an existing ItemLabelDetails instance
     * @param other The existing instance to copy.
     */
    private Builder(com.integrations.orderprocessing.kafka.schema.ItemLabelDetails other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.cartonLabelId)) {
        this.cartonLabelId = data().deepCopy(fields()[0].schema(), other.cartonLabelId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.labelType)) {
        this.labelType = data().deepCopy(fields()[1].schema(), other.labelType);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.palletLabelId)) {
        this.palletLabelId = data().deepCopy(fields()[2].schema(), other.palletLabelId);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.palletNumber)) {
        this.palletNumber = data().deepCopy(fields()[3].schema(), other.palletNumber);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.quantity)) {
        this.quantity = data().deepCopy(fields()[4].schema(), other.quantity);
        fieldSetFlags()[4] = true;
      }
    }

    /**
      * Gets the value of the 'cartonLabelId' field.
      * @return The value.
      */
    public java.lang.String getCartonLabelId() {
      return cartonLabelId;
    }


    /**
      * Sets the value of the 'cartonLabelId' field.
      * @param value The value of 'cartonLabelId'.
      * @return This builder.
      */
    public com.integrations.orderprocessing.kafka.schema.ItemLabelDetails.Builder setCartonLabelId(java.lang.String value) {
      validate(fields()[0], value);
      this.cartonLabelId = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'cartonLabelId' field has been set.
      * @return True if the 'cartonLabelId' field has been set, false otherwise.
      */
    public boolean hasCartonLabelId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'cartonLabelId' field.
      * @return This builder.
      */
    public com.integrations.orderprocessing.kafka.schema.ItemLabelDetails.Builder clearCartonLabelId() {
      cartonLabelId = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'labelType' field.
      * @return The value.
      */
    public java.lang.String getLabelType() {
      return labelType;
    }


    /**
      * Sets the value of the 'labelType' field.
      * @param value The value of 'labelType'.
      * @return This builder.
      */
    public com.integrations.orderprocessing.kafka.schema.ItemLabelDetails.Builder setLabelType(java.lang.String value) {
      validate(fields()[1], value);
      this.labelType = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'labelType' field has been set.
      * @return True if the 'labelType' field has been set, false otherwise.
      */
    public boolean hasLabelType() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'labelType' field.
      * @return This builder.
      */
    public com.integrations.orderprocessing.kafka.schema.ItemLabelDetails.Builder clearLabelType() {
      labelType = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'palletLabelId' field.
      * @return The value.
      */
    public java.lang.String getPalletLabelId() {
      return palletLabelId;
    }


    /**
      * Sets the value of the 'palletLabelId' field.
      * @param value The value of 'palletLabelId'.
      * @return This builder.
      */
    public com.integrations.orderprocessing.kafka.schema.ItemLabelDetails.Builder setPalletLabelId(java.lang.String value) {
      validate(fields()[2], value);
      this.palletLabelId = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'palletLabelId' field has been set.
      * @return True if the 'palletLabelId' field has been set, false otherwise.
      */
    public boolean hasPalletLabelId() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'palletLabelId' field.
      * @return This builder.
      */
    public com.integrations.orderprocessing.kafka.schema.ItemLabelDetails.Builder clearPalletLabelId() {
      palletLabelId = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'palletNumber' field.
      * @return The value.
      */
    public java.lang.String getPalletNumber() {
      return palletNumber;
    }


    /**
      * Sets the value of the 'palletNumber' field.
      * @param value The value of 'palletNumber'.
      * @return This builder.
      */
    public com.integrations.orderprocessing.kafka.schema.ItemLabelDetails.Builder setPalletNumber(java.lang.String value) {
      validate(fields()[3], value);
      this.palletNumber = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'palletNumber' field has been set.
      * @return True if the 'palletNumber' field has been set, false otherwise.
      */
    public boolean hasPalletNumber() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'palletNumber' field.
      * @return This builder.
      */
    public com.integrations.orderprocessing.kafka.schema.ItemLabelDetails.Builder clearPalletNumber() {
      palletNumber = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'quantity' field.
      * @return The value.
      */
    public int getQuantity() {
      return quantity;
    }


    /**
      * Sets the value of the 'quantity' field.
      * @param value The value of 'quantity'.
      * @return This builder.
      */
    public com.integrations.orderprocessing.kafka.schema.ItemLabelDetails.Builder setQuantity(int value) {
      validate(fields()[4], value);
      this.quantity = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'quantity' field has been set.
      * @return True if the 'quantity' field has been set, false otherwise.
      */
    public boolean hasQuantity() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'quantity' field.
      * @return This builder.
      */
    public com.integrations.orderprocessing.kafka.schema.ItemLabelDetails.Builder clearQuantity() {
      fieldSetFlags()[4] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public ItemLabelDetails build() {
      try {
        ItemLabelDetails record = new ItemLabelDetails();
        record.cartonLabelId = fieldSetFlags()[0] ? this.cartonLabelId : (java.lang.String) defaultValue(fields()[0]);
        record.labelType = fieldSetFlags()[1] ? this.labelType : (java.lang.String) defaultValue(fields()[1]);
        record.palletLabelId = fieldSetFlags()[2] ? this.palletLabelId : (java.lang.String) defaultValue(fields()[2]);
        record.palletNumber = fieldSetFlags()[3] ? this.palletNumber : (java.lang.String) defaultValue(fields()[3]);
        record.quantity = fieldSetFlags()[4] ? this.quantity : (java.lang.Integer) defaultValue(fields()[4]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<ItemLabelDetails>
    WRITER$ = (org.apache.avro.io.DatumWriter<ItemLabelDetails>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<ItemLabelDetails>
    READER$ = (org.apache.avro.io.DatumReader<ItemLabelDetails>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.cartonLabelId);

    out.writeString(this.labelType);

    out.writeString(this.palletLabelId);

    out.writeString(this.palletNumber);

    out.writeInt(this.quantity);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.cartonLabelId = in.readString();

      this.labelType = in.readString();

      this.palletLabelId = in.readString();

      this.palletNumber = in.readString();

      this.quantity = in.readInt();

    } else {
      for (int i = 0; i < 5; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.cartonLabelId = in.readString();
          break;

        case 1:
          this.labelType = in.readString();
          break;

        case 2:
          this.palletLabelId = in.readString();
          break;

        case 3:
          this.palletNumber = in.readString();
          break;

        case 4:
          this.quantity = in.readInt();
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










