/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.integrations.orderprocessing.kafka.schema;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class ShpmentConfInGoodsActvtsIssueToDlvry extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -2637110603106087868L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"ShpmentConfInGoodsActvtsIssueToDlvry\",\"namespace\":\"com.integrations.orderprocessing.kafka.schema\",\"fields\":[{\"name\":\"shippedDeliveryDate\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<ShpmentConfInGoodsActvtsIssueToDlvry> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<ShpmentConfInGoodsActvtsIssueToDlvry> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<ShpmentConfInGoodsActvtsIssueToDlvry> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<ShpmentConfInGoodsActvtsIssueToDlvry> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<ShpmentConfInGoodsActvtsIssueToDlvry> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this ShpmentConfInGoodsActvtsIssueToDlvry to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a ShpmentConfInGoodsActvtsIssueToDlvry from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a ShpmentConfInGoodsActvtsIssueToDlvry instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static ShpmentConfInGoodsActvtsIssueToDlvry fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private java.lang.String shippedDeliveryDate;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public ShpmentConfInGoodsActvtsIssueToDlvry() {}

  /**
   * All-args constructor.
   * @param shippedDeliveryDate The new value for shippedDeliveryDate
   */
  public ShpmentConfInGoodsActvtsIssueToDlvry(java.lang.String shippedDeliveryDate) {
    this.shippedDeliveryDate = shippedDeliveryDate;
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return shippedDeliveryDate;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: shippedDeliveryDate = value$ != null ? value$.toString() : null; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'shippedDeliveryDate' field.
   * @return The value of the 'shippedDeliveryDate' field.
   */
  public java.lang.String getShippedDeliveryDate() {
    return shippedDeliveryDate;
  }


  /**
   * Sets the value of the 'shippedDeliveryDate' field.
   * @param value the value to set.
   */
  public void setShippedDeliveryDate(java.lang.String value) {
    this.shippedDeliveryDate = value;
  }

  /**
   * Creates a new ShpmentConfInGoodsActvtsIssueToDlvry RecordBuilder.
   * @return A new ShpmentConfInGoodsActvtsIssueToDlvry RecordBuilder
   */
  public static com.integrations.orderprocessing.kafka.schema.ShpmentConfInGoodsActvtsIssueToDlvry.Builder newBuilder() {
    return new com.integrations.orderprocessing.kafka.schema.ShpmentConfInGoodsActvtsIssueToDlvry.Builder();
  }

  /**
   * Creates a new ShpmentConfInGoodsActvtsIssueToDlvry RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new ShpmentConfInGoodsActvtsIssueToDlvry RecordBuilder
   */
  public static com.integrations.orderprocessing.kafka.schema.ShpmentConfInGoodsActvtsIssueToDlvry.Builder newBuilder(com.integrations.orderprocessing.kafka.schema.ShpmentConfInGoodsActvtsIssueToDlvry.Builder other) {
    if (other == null) {
      return new com.integrations.orderprocessing.kafka.schema.ShpmentConfInGoodsActvtsIssueToDlvry.Builder();
    } else {
      return new com.integrations.orderprocessing.kafka.schema.ShpmentConfInGoodsActvtsIssueToDlvry.Builder(other);
    }
  }

  /**
   * Creates a new ShpmentConfInGoodsActvtsIssueToDlvry RecordBuilder by copying an existing ShpmentConfInGoodsActvtsIssueToDlvry instance.
   * @param other The existing instance to copy.
   * @return A new ShpmentConfInGoodsActvtsIssueToDlvry RecordBuilder
   */
  public static com.integrations.orderprocessing.kafka.schema.ShpmentConfInGoodsActvtsIssueToDlvry.Builder newBuilder(com.integrations.orderprocessing.kafka.schema.ShpmentConfInGoodsActvtsIssueToDlvry other) {
    if (other == null) {
      return new com.integrations.orderprocessing.kafka.schema.ShpmentConfInGoodsActvtsIssueToDlvry.Builder();
    } else {
      return new com.integrations.orderprocessing.kafka.schema.ShpmentConfInGoodsActvtsIssueToDlvry.Builder(other);
    }
  }

  /**
   * RecordBuilder for ShpmentConfInGoodsActvtsIssueToDlvry instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<ShpmentConfInGoodsActvtsIssueToDlvry>
    implements org.apache.avro.data.RecordBuilder<ShpmentConfInGoodsActvtsIssueToDlvry> {

    private java.lang.String shippedDeliveryDate;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.integrations.orderprocessing.kafka.schema.ShpmentConfInGoodsActvtsIssueToDlvry.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.shippedDeliveryDate)) {
        this.shippedDeliveryDate = data().deepCopy(fields()[0].schema(), other.shippedDeliveryDate);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
    }

    /**
     * Creates a Builder by copying an existing ShpmentConfInGoodsActvtsIssueToDlvry instance
     * @param other The existing instance to copy.
     */
    private Builder(com.integrations.orderprocessing.kafka.schema.ShpmentConfInGoodsActvtsIssueToDlvry other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.shippedDeliveryDate)) {
        this.shippedDeliveryDate = data().deepCopy(fields()[0].schema(), other.shippedDeliveryDate);
        fieldSetFlags()[0] = true;
      }
    }

    /**
      * Gets the value of the 'shippedDeliveryDate' field.
      * @return The value.
      */
    public java.lang.String getShippedDeliveryDate() {
      return shippedDeliveryDate;
    }


    /**
      * Sets the value of the 'shippedDeliveryDate' field.
      * @param value The value of 'shippedDeliveryDate'.
      * @return This builder.
      */
    public com.integrations.orderprocessing.kafka.schema.ShpmentConfInGoodsActvtsIssueToDlvry.Builder setShippedDeliveryDate(java.lang.String value) {
      validate(fields()[0], value);
      this.shippedDeliveryDate = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'shippedDeliveryDate' field has been set.
      * @return True if the 'shippedDeliveryDate' field has been set, false otherwise.
      */
    public boolean hasShippedDeliveryDate() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'shippedDeliveryDate' field.
      * @return This builder.
      */
    public com.integrations.orderprocessing.kafka.schema.ShpmentConfInGoodsActvtsIssueToDlvry.Builder clearShippedDeliveryDate() {
      shippedDeliveryDate = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public ShpmentConfInGoodsActvtsIssueToDlvry build() {
      try {
        ShpmentConfInGoodsActvtsIssueToDlvry record = new ShpmentConfInGoodsActvtsIssueToDlvry();
        record.shippedDeliveryDate = fieldSetFlags()[0] ? this.shippedDeliveryDate : (java.lang.String) defaultValue(fields()[0]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<ShpmentConfInGoodsActvtsIssueToDlvry>
    WRITER$ = (org.apache.avro.io.DatumWriter<ShpmentConfInGoodsActvtsIssueToDlvry>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<ShpmentConfInGoodsActvtsIssueToDlvry>
    READER$ = (org.apache.avro.io.DatumReader<ShpmentConfInGoodsActvtsIssueToDlvry>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.shippedDeliveryDate);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.shippedDeliveryDate = in.readString();

    } else {
      for (int i = 0; i < 1; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.shippedDeliveryDate = in.readString();
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










